name: google_mlkit_face_detection_example
description: Example app for the google_mlkit_face_detection plugin
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true