name: google_mlkit_face_detection
description: "A Flutter plugin to use Google's ML Kit Face Detection to detect faces in an image, identify key facial features, and get the contours of detected faces."
version: 0.13.1
publish_to: none
homepage: https://github.com/flutter-ml/google_ml_kit_flutter
repository: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_face_detection

environment:
  sdk: ^3.9.2
  flutter: "3.35.4"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: 
    git: https://github.com/ahmed-mohamed-25/google_mlkit_commons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_face_detection
        pluginClass: GoogleMlKitFaceDetectionPlugin
      ios:
        pluginClass: GoogleMlKitFaceDetectionPlugin
